### ISSUE TITLE
BDD100K  MOT Challenge

### ISSUE THREAD

**Issue by zhaowujie** [ucbdrive/bdd100k#85]
**Hello, I'm in the BDD100K  MOT Challenge,but my score is low, is there any problem with my results format?**
#
`[{"name": "cabc30fc-e7726578-0000001.jpg", "labels": [{"id": "00000001", "category": "car", "box2d": {"x1": 750.6703491210938, "y1": 432.6123046875, "x2": 802.6581420898438, "y2": 449.479736328125}}, {"id": "00000020", "category": "car", "box2d": {"x1": 605.9588623046875, "y1": 432.7497253417969, "x2": 641.789306640625, "y2": 465.9720153808594}}, {"id": "00000089", "category": "car", "box2d": {"x1": 636.473388671875, "y1": 418.732666015625, "x2": 742.8145751953125, "y2": 511.1887512207031}}]}, {"name": "cabc30fc-e7726578-0000002.jpg", .............]`

**By the way, is there any submission example file, thanks a lot!!!** @fyu @yuandong

**Comment by xanderchf** [comment]
Hello,

An example submission is at
http://dl.yf.io/bdd100k/bdd100k_tracking20_val_example_submission.json. We
will also release this soon on our website.

Best,
Haofeng

**Comment by fyu** [comment]
@zhaowujie you can also use `show_labels` to visualize and check your results. An example usage

```
python3 -m bdd100k.show_labels --image-dir bdd100k/images/100k/train \
    -l bdd100k/labels/bdd100k_labels_images_train.json
```

**Comment by zhaowujie** [comment]
Thanks a lot!!! @fyu @xanderchf
