### ISSUE TITLE
About the WAD 2018 Challenges

### ISSUE THREAD

**Issue by winnerCR7** [ucbdrive/bdd100k#93]
Hi,
How do you define the scores in the three tasks of Drivable Area, Road Object Detection, and Domain Adaption in WAD 2018 Challenges? [https://bdd-data.berkeley.edu/wad-2018.html](url)

**Comment by fyu** [comment]
Drivable area and segmentation domain adaptation were evaluated based on IoU. Road object detection uses AP75.
