### ISSUE TITLE
Show labels does not iterate over labels 

### ISSUE THREAD

**Issue by isht7** [ucbdrive/bdd100k#96]
When I run
`python3 -m bdd100k.show_labels --image-dir bdd100k/images/100k/train \
    -l bdd100k/labels/bdd100k_labels_images_train.json`
it shows labels for only 1 image and then the program ends. According to instructions, it should loop over different images.

Edit: The program works and shows the next image when we press 'n' and shows previous image when we press 'p'. Maybe this could be written in the readme, as I have to look at the code to figure this out and it was not obvious to me.
Thanks!

**Comment by isht7** [comment]
Issue solved, closing. (see the Edit part of the issue above). Thanks.

**Comment by fyu** [comment]
Thanks for the suggestion!
